#+TITLE: Rational Spirit

/This book is under development./

* Introduction

We live in confusing times.

You may be wondering: 
What is real?
How can I know anything?
What is consciousness?
Is there such a thing as right and wrong? 
Is there a God?
What is the most just form of human government?

This book has answers to all these questions,
and provides some reasons for those answers.

** Is this book religious?

Maybe.

This book is intended to be consistent with the foundations
of mainstream secular scientific education.

However, it draws conclusions from those foundations that
are more associated with religion than science.

It does not depend logically on any particular religious authority.
However, where a word from a religious tradition seems appropriate
for a concept in this book, I use it.

** Who are you to write this book?

I am somebody who has studied philosophy, science, 
and religion quite seriously for a lot of their life. 

I have come to some interesting conclusions that 
I would like to share with you.

* How can I know anything?

This is a good question to start with.
The best advice is to work with what you've got.
You already have some practical understanding of how to come to know things.
Don't lose it!

Bayesian updating and mathematical proof.

Also, social trust in expertise. (Peirce, 1877)

* What is real?

Most of what you experience every day is real.
I am not writing to tell you that your world is illusory.
Whatever you are sitting on is real.
The device you are using to read this book is real.

*** If a tree falls in a forest, and nobody is there to hear it, does it make as sound?

Yes.

** Why is there something instead of nothing?

There's both something and /also/ nothing.

But you are in the something part.

* What is consciousness?

Consciousness is integration of situated information flows.

* Is there such a thing as right and wrong? 

Yes.

** Why?

Because after you die your consciousness is recycled into other forms,
and so enlightened self-interest requires you to improve the lot of others.

This is karma.

* Is there a God?

Yes.

** Really?

Yeah, I mean, why not?

** Why is there evil in the world if God is good?

Because of bad karma.

* What is the most just form of human government?

TBD.


* Other questions

** Will artificial intelligence cause an existential risk to humanity?

Probably not.

* Bibliography

Kant, Immanuel. "Critique of pure reason. 1781." Modern Classical Philosophers, Cambridge, MA: Houghton Mifflin (1908): 370-456.

Peirce, Charles Sanders. "The fixation of belief." 1877.
