#+TITLE: Rational Spirit

/This book is under development./

We live in confusing times.

You may be wondering: 
What is real?
How can I know anything?
What is consciousness?
Is there such a thing as right and wrong? 
Is there a God?
What is the most just form of human government?

This book has answers to all these questions,
and provides an argument for those answers.

* Who are you to write this book?

I am somebody who has studied philosophy, science, 
and religion quite seriously for a lot of their life. 

I have come to some interesting conclusions that 
I would like to share with you.

* What is real?

The normal stuff.

** Is it material or ideal?

It's ideal. Everything is in "the mind".

** Why is there something instead of nothing?

There's both something and /also/ nothing.

But you are in the something part.

* How can I know anything?

Bayesian updating and mathematical proof.

Also, social trust in expertise.

# See cite:peirce1877fixation

* What is consciousness?

Consciousness is integration of situated information flows.

* Is there such a thing as right and wrong? 

Yes.

** Why?

Because after you die your consciousness is recycled into other forms,
and so enlightened self-interest requires you to improve the lot of others.

This is karma.

* Is there a God?

Yes.

** Really?

Yeah, I mean, why not?

** Why is there evil in the world if God is good?

Because of bad karma.

* What is the most just form of human government?

TBD.



# * Bibliography
#
# bibliography:rs.bib
